<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Rest-Assured-DATA-DRIVEN-TESTING" duration-ms="52691" started-at="2022-01-08T22:50:59 CST" finished-at="2022-01-08T22:51:52 CST">
    <groups>
    </groups>
    <test name="generateExtentReports" duration-ms="52691" started-at="2022-01-08T22:50:59 CST" finished-at="2022-01-08T22:51:52 CST">
      <class name="test.PutEmployeeData">
        <test-method status="PASS" signature="logMaker()[pri:0, instance:test.PutEmployeeData@47faa49c]" name="logMaker" is-config="true" duration-ms="2" started-at="2022-01-08T22:51:36 CST" finished-at="2022-01-08T22:51:36 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logMaker -->
        <test-method status="FAIL" signature="putEmployeeData(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:3, instance:test.PutEmployeeData@47faa49c]" name="putEmployeeData" duration-ms="14503" started-at="2022-01-08T22:51:37 CST" data-provider="empChange" finished-at="2022-01-08T22:51:51 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[GolGappa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[WastePicker]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[49]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [429]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at test.PutEmployeeData.putEmployeeData(PutEmployeeData.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putEmployeeData -->
      </class> <!-- test.PutEmployeeData -->
      <class name="test.DeleteEmployeeData">
        <test-method status="PASS" signature="logMaker()[pri:0, instance:test.DeleteEmployeeData@28f2a10f]" name="logMaker" is-config="true" duration-ms="5" started-at="2022-01-08T22:51:51 CST" finished-at="2022-01-08T22:51:51 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logMaker -->
        <test-method status="PASS" signature="deleteEmployee()[pri:4, instance:test.DeleteEmployeeData@28f2a10f]" name="deleteEmployee" duration-ms="751" started-at="2022-01-08T22:51:51 CST" finished-at="2022-01-08T22:51:52 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployee -->
      </class> <!-- test.DeleteEmployeeData -->
      <class name="test.GetEmployeeData">
        <test-method status="PASS" signature="logMaker()[pri:0, instance:test.GetEmployeeData@4d465b11]" name="logMaker" is-config="true" duration-ms="25" started-at="2022-01-08T22:51:00 CST" finished-at="2022-01-08T22:51:00 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logMaker -->
        <test-method status="FAIL" signature="empData([Ljava.lang.String;)[pri:1, instance:test.GetEmployeeData@4d465b11]" name="empData" duration-ms="4633" started-at="2022-01-08T22:51:00 CST" data-provider="Jps" finished-at="2022-01-08T22:51:04 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@53f4c1e6]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<429> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:468)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:318)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:328)
at test.GetEmployeeData.empData(GetEmployeeData.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- empData -->
        <test-method status="FAIL" signature="empData([Ljava.lang.String;)[pri:1, instance:test.GetEmployeeData@4d465b11]" name="empData" duration-ms="3019" started-at="2022-01-08T22:51:04 CST" data-provider="Jps" finished-at="2022-01-08T22:51:07 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@5a6fa56e]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<429> but was:<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:468)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:318)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:328)
at test.GetEmployeeData.empData(GetEmployeeData.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- empData -->
      </class> <!-- test.GetEmployeeData -->
      <class name="test.PostEmployeeData">
        <test-method status="PASS" signature="logMaker()[pri:0, instance:test.PostEmployeeData@73e22a3d]" name="logMaker" is-config="true" duration-ms="5" started-at="2022-01-08T22:51:07 CST" finished-at="2022-01-08T22:51:07 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logMaker -->
        <test-method status="PASS" signature="postEmployeeData([Ljava.lang.String;)[pri:2, instance:test.PostEmployeeData@73e22a3d]" name="postEmployeeData" duration-ms="21690" started-at="2022-01-08T22:51:07 CST" data-provider="Jps" finished-at="2022-01-08T22:51:29 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@74174a23]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postEmployeeData -->
        <test-method status="PASS" signature="postEmployeeData([Ljava.lang.String;)[pri:2, instance:test.PostEmployeeData@73e22a3d]" name="postEmployeeData" duration-ms="6720" started-at="2022-01-08T22:51:29 CST" data-provider="Jps" finished-at="2022-01-08T22:51:36 CST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@6342d610]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postEmployeeData -->
      </class> <!-- test.PostEmployeeData -->
    </test> <!-- generateExtentReports -->
  </suite> <!-- Rest-Assured-DATA-DRIVEN-TESTING -->
</testng-results>
